apiVersion: v1
kind: ConfigMap
metadata:
  name: project-configmap
  namespace: project
data:
  PORT: "8080"
  BACKEND_PORT: "8081"
  IMAGE_URL: "https://picsum.photos/1200"
  IMAGE_PATH: "/app/shared/image.jpg"
